### ISSUE TITLE
Fails to build with aeson-1.2.2.0

### ISSUE THREAD

**Issue by juhp** [GregorySchwartz/find-clumpiness#3]
```
Building executable 'find-clumpiness' for find-clumpiness-0.2.3.0..
[1 of 1] Compiling Main             ( app/Main.hs, dist/build/find-clumpiness/find-clumpiness-tmp/Main.o )

app/Main.hs:44:19: error:
    Ambiguous occurrence ‘Options’
    It could refer to either ‘Data.Aeson.Options’,
                             imported from ‘Data.Aeson’ at app/Main.hs:9:1-17
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Main.Options’, defined at app/Main.hs:34:1
   |
44 | options :: Parser Options
   |                   ^^^^^^^

app/Main.hs:115:18: error:
    Ambiguous occurrence ‘Options’
```

**Comment by juhp** [comment]
See fpco/stackage#2879

**Comment by GregorySchwartz** [comment]
Fixed in find-clumpiness-0.2.3.1.
